project_name: k8s-kms-plugin

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - LATEST_TAG=,latest

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy
    - go mod download

# Generate SBOM for all artifacts
sboms:
  - artifacts: binary
# Build the k8s-kms-plugin in differents architecture
builds:
  - id: linux
    binary: k8s-kms-plugin-linux-{{ .Arch }}
    no_unique_dist_dir: true
    main: ./cmd/k8s-kms-plugin/main.go
    
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"

# Define caracteristics of binary artifacts
archives:
  - format: binary
    name_template: "{{ .Binary }}" 
    allow_different_binary_count: true

# Checksum caracteristics
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
# Snapshot caracteristics
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
# Sign the artifacts
signs:
  - signature: "${artifact}.sig"
    args: ["--output", "${signature}", "${artifact}", "{{ .ProjectName }}"]
    artifacts: all
    certificate: "${artifact}-keyless.pem"

# Create a release 
release:
  github:
    owner: louison77
    name: k8s-kms-plugin
  replace_existing_draft: true
  footer: |
    ### Thanks to all contributors!

