project_name: k8s-kms-plugin

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - LATEST_TAG=,latest

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy
    - go mod download

sboms:
  - artifacts: binary

builds:
  - id: linux
    binary: k8s-kms-plugin-linux-{{ .Arch }}
    no_unique_dist_dir: true
    main: ./cmd/k8s-kms-plugin/main.go
    
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=1

archives:
  - format: binary
    name_template: "{{ .Binary }}" 
    allow_different_binary_count: true

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}


release:
  
  github:
    owner: louison77
    name: k8s-kms-plugin
  replace_existing_draft: true
  footer: |
    ### Thanks to all contributors!

