project_name: k8s-kms-plugin

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - LATEST_TAG=,latest

# Prevents parallel builds from stepping on each others toes downloading modules
before:
  hooks:
    - go mod tidy
    - go mod download

# Generate SBOM for all artifacts
sboms:
  - artifacts: binary
# Build the k8s-kms-plugin in differents architecture
builds:
  - id: linux
    binary: k8s-kms-plugin-linux-{{ .Arch }}_{{ .Version }}
    no_unique_dist_dir: true
    main: ./cmd/k8s-kms-plugin/main.go
    
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
nfpms:
  - id: k8s-kms-plugin
    package_name: k8s-kms-plugin
    file_name_template:  "{{ .ConventionalFileName }}"
    license: "Apache License 2.0"
    maintainer: ThalesGroup
    builds:
      - linux
    formats:
        - apk
        - deb
        - rpm
    contents:
        - src: /usr/bin/k8s-kms-plugin-linux-{{ .Arch }}_{{ .Version }}
          dst: /usr/bin/k8s-kms-plugin
          type: "symlink"


# Define caracteristics of binary artifacts
archives:
  - format: binary
    name_template: "{{ .Binary }}" 
    allow_different_binary_count: true
# create metadata file
metadata:
  
  mod_timestamp: "{{ .CommitTimestamp }}"


# Checksum caracteristics
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
# Snapshot caracteristics
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

# Sign the artifacts
signs:
  - id : k8s-kms-plugin-keyless
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    signature : "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "-y"
      - "${artifact}"   
    artifacts: binary
    output: true
  - id : checksum-keyless
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    signature : "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "-y"
      - "${artifact}"   
    artifacts: checksum
    output: true
  - id : package-keyless
    cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    signature : "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "-y"
      - "${artifact}" 
    artifacts: package
    output: true

# Create a release 
release:
  github:
    owner: louison77
    name: k8s-kms-plugin
  replace_existing_draft: true
  footer: |
    ### Thanks to all contributors!

