---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          apiVersion: v2
          name: kms-server
          endpoint: https://127.0.0.1:8842
          timeout: 3s
      - identity: {}