// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCACertsHandlerFunc turns a function with the right signature into a get c a certs handler
type GetCACertsHandlerFunc func(GetCACertsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCACertsHandlerFunc) Handle(params GetCACertsParams) middleware.Responder {
	return fn(params)
}

// GetCACertsHandler interface for that can handle valid get c a certs params
type GetCACertsHandler interface {
	Handle(GetCACertsParams) middleware.Responder
}

// NewGetCACerts creates a new http.Handler for the get c a certs operation
func NewGetCACerts(ctx *middleware.Context, handler GetCACertsHandler) *GetCACerts {
	return &GetCACerts{Context: ctx, Handler: handler}
}

/*GetCACerts swagger:route GET /cacerts operation getCACerts

Distribution of CA Certificates

Distributes CA Certificate chain for this Service

*/
type GetCACerts struct {
	Context *middleware.Context
	Handler GetCACertsHandler
}

func (o *GetCACerts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCACertsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
