// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCACertsParams creates a new GetCACertsParams object
// with the default values initialized.
func NewGetCACertsParams() *GetCACertsParams {

	return &GetCACertsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCACertsParamsWithTimeout creates a new GetCACertsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCACertsParamsWithTimeout(timeout time.Duration) *GetCACertsParams {

	return &GetCACertsParams{

		timeout: timeout,
	}
}

// NewGetCACertsParamsWithContext creates a new GetCACertsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCACertsParamsWithContext(ctx context.Context) *GetCACertsParams {

	return &GetCACertsParams{

		Context: ctx,
	}
}

// NewGetCACertsParamsWithHTTPClient creates a new GetCACertsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCACertsParamsWithHTTPClient(client *http.Client) *GetCACertsParams {

	return &GetCACertsParams{
		HTTPClient: client,
	}
}

/*GetCACertsParams contains all the parameters to send to the API endpoint
for the get c a certs operation typically these are written to a http.Request
*/
type GetCACertsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get c a certs params
func (o *GetCACertsParams) WithTimeout(timeout time.Duration) *GetCACertsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get c a certs params
func (o *GetCACertsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get c a certs params
func (o *GetCACertsParams) WithContext(ctx context.Context) *GetCACertsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get c a certs params
func (o *GetCACertsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get c a certs params
func (o *GetCACertsParams) WithHTTPClient(client *http.Client) *GetCACertsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get c a certs params
func (o *GetCACertsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCACertsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
