// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operation API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operation API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetCACerts(params *GetCACertsParams) (*GetCACertsOK, error)

	Simpleenroll(params *SimpleenrollParams, authInfo runtime.ClientAuthInfoWriter) (*SimpleenrollOK, error)

	Simplereenroll(params *SimplereenrollParams) (*SimplereenrollOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetCACerts distributions of c a certificates

  Distributes CA Certificate chain for this Service
*/
func (a *Client) GetCACerts(params *GetCACertsParams) (*GetCACertsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCACertsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetCACerts",
		Method:             "GET",
		PathPattern:        "/cacerts",
		ProducesMediaTypes: []string{"application/pkcs7-mime"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCACertsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCACertsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCACerts: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Simpleenroll enrollments of clients
*/
func (a *Client) Simpleenroll(params *SimpleenrollParams, authInfo runtime.ClientAuthInfoWriter) (*SimpleenrollOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSimpleenrollParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "simpleenroll",
		Method:             "POST",
		PathPattern:        "/simpleenroll",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/pkcs10"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SimpleenrollReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SimpleenrollOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for simpleenroll: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Simplereenroll enrollments of clients requires mutual tls
*/
func (a *Client) Simplereenroll(params *SimplereenrollParams) (*SimplereenrollOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSimplereenrollParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "simplereenroll",
		Method:             "POST",
		PathPattern:        "/simplereenroll",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/pkcs10"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SimplereenrollReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SimplereenrollOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for simplereenroll: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
