//
//Copyright 2018 The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.10.0
// source: apis/istio/v1/messages.proto

package istio

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KeyKind int32

const (
	KeyKind_UNKNOWN KeyKind = 0
	KeyKind_AES     KeyKind = 1
	KeyKind_RSA     KeyKind = 2
	KeyKind_ECC     KeyKind = 3
)

// Enum value maps for KeyKind.
var (
	KeyKind_name = map[int32]string{
		0: "UNKNOWN",
		1: "AES",
		2: "RSA",
		3: "ECC",
	}
	KeyKind_value = map[string]int32{
		"UNKNOWN": 0,
		"AES":     1,
		"RSA":     2,
		"ECC":     3,
	}
)

func (x KeyKind) Enum() *KeyKind {
	p := new(KeyKind)
	*p = x
	return p
}

func (x KeyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_istio_v1_messages_proto_enumTypes[0].Descriptor()
}

func (KeyKind) Type() protoreflect.EnumType {
	return &file_apis_istio_v1_messages_proto_enumTypes[0]
}

func (x KeyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyKind.Descriptor instead.
func (KeyKind) EnumDescriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{0}
}

type GenerateKEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// optional kid, otherwise will be autogenerated as a UUID.v4 in the response
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *GenerateKEKRequest) Reset() {
	*x = GenerateKEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEKRequest) ProtoMessage() {}

func (x *GenerateKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEKRequest.ProtoReflect.Descriptor instead.
func (*GenerateKEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type GenerateKEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// KEK kid
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *GenerateKEKResponse) Reset() {
	*x = GenerateKEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEKResponse) ProtoMessage() {}

func (x *GenerateKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEKResponse.ProtoReflect.Descriptor instead.
func (*GenerateKEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKEKResponse) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyKEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required kid of KEK to find and delete
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *DestroyKEKRequest) Reset() {
	*x = DestroyKEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEKRequest) ProtoMessage() {}

func (x *DestroyKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEKRequest.ProtoReflect.Descriptor instead.
func (*DestroyKEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyKEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyKEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// successful destroy?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DestroyKEKResponse) Reset() {
	*x = DestroyKEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEKResponse) ProtoMessage() {}

func (x *DestroyKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEKResponse.ProtoReflect.Descriptor instead.
func (*DestroyKEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyKEKResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GenerateDEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key size in bits
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// What kind of key is it... only Symmetric kinds will be supported
	Kind KeyKind `protobuf:"varint,2,opt,name=kind,proto3,enum=thalescpl.io.ekms.istio.v1.KeyKind" json:"kind,omitempty"`
	// Parent KID of the KEK
	KekKid []byte `protobuf:"bytes,3,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *GenerateDEKRequest) Reset() {
	*x = GenerateDEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDEKRequest) ProtoMessage() {}

func (x *GenerateDEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDEKRequest.ProtoReflect.Descriptor instead.
func (*GenerateDEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateDEKRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateDEKRequest) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_UNKNOWN
}

func (x *GenerateDEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type GenerateDEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Encrypted key blob
	EncryptedDekBlob []byte `protobuf:"bytes,1,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
}

func (x *GenerateDEKResponse) Reset() {
	*x = GenerateDEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDEKResponse) ProtoMessage() {}

func (x *GenerateDEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDEKResponse.ProtoReflect.Descriptor instead.
func (*GenerateDEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateDEKResponse) GetEncryptedDekBlob() []byte {
	if x != nil {
		return x.EncryptedDekBlob
	}
	return nil
}

type GenerateCAKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key size in bits
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// What kind of key is it... only Asymmetric kinds will be supported
	Kind KeyKind `protobuf:"varint,2,opt,name=kind,proto3,enum=thalescpl.io.ekms.istio.v1.KeyKind" json:"kind,omitempty"`
	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,3,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *GenerateCAKRequest) Reset() {
	*x = GenerateCAKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCAKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCAKRequest) ProtoMessage() {}

func (x *GenerateCAKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCAKRequest.ProtoReflect.Descriptor instead.
func (*GenerateCAKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateCAKRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateCAKRequest) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_UNKNOWN
}

func (x *GenerateCAKRequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type GenerateCAKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,1,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *GenerateCAKResponse) Reset() {
	*x = GenerateCAKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCAKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCAKResponse) ProtoMessage() {}

func (x *GenerateCAKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCAKResponse.ProtoReflect.Descriptor instead.
func (*GenerateCAKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateCAKResponse) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type GenerateCARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,1,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *GenerateCARequest) Reset() {
	*x = GenerateCARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCARequest) ProtoMessage() {}

func (x *GenerateCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCARequest.ProtoReflect.Descriptor instead.
func (*GenerateCARequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateCARequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type GenerateCAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Root CA cert in PEM format
	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *GenerateCAResponse) Reset() {
	*x = GenerateCAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCAResponse) ProtoMessage() {}

func (x *GenerateCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCAResponse.ProtoReflect.Descriptor instead.
func (*GenerateCAResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateCAResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

type DestroyRootCAKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required kid of KEK to find and delete
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *DestroyRootCAKRequest) Reset() {
	*x = DestroyRootCAKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRootCAKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRootCAKRequest) ProtoMessage() {}

func (x *DestroyRootCAKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRootCAKRequest.ProtoReflect.Descriptor instead.
func (*DestroyRootCAKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyRootCAKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyRootCAKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// successful destroy?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DestroyRootCAKResponse) Reset() {
	*x = DestroyRootCAKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyRootCAKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRootCAKResponse) ProtoMessage() {}

func (x *DestroyRootCAKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRootCAKResponse.ProtoReflect.Descriptor instead.
func (*DestroyRootCAKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyRootCAKResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GenerateSEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key size in bits
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// What kind of key is it... only Asymmetric kinds will be supported
	Kind KeyKind `protobuf:"varint,2,opt,name=kind,proto3,enum=thalescpl.io.ekms.istio.v1.KeyKind" json:"kind,omitempty"`
	// Encrypted blob of DEK
	EncryptedDekBlob []byte `protobuf:"bytes,3,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	// Encrypted blob of SEK
	EncryptedSekBlob []byte `protobuf:"bytes,4,opt,name=encrypted_sek_blob,json=encryptedSekBlob,proto3" json:"encrypted_sek_blob,omitempty"`
	// Parent KID of the KEK
	KekKid []byte `protobuf:"bytes,5,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *GenerateSEKRequest) Reset() {
	*x = GenerateSEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSEKRequest) ProtoMessage() {}

func (x *GenerateSEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSEKRequest.ProtoReflect.Descriptor instead.
func (*GenerateSEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateSEKRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateSEKRequest) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_UNKNOWN
}

func (x *GenerateSEKRequest) GetEncryptedDekBlob() []byte {
	if x != nil {
		return x.EncryptedDekBlob
	}
	return nil
}

func (x *GenerateSEKRequest) GetEncryptedSekBlob() []byte {
	if x != nil {
		return x.EncryptedSekBlob
	}
	return nil
}

func (x *GenerateSEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type GenerateSEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Encrypted blob of SEK encrypted by DEK
	EncryptedSekBlob []byte `protobuf:"bytes,1,opt,name=encrypted_sek_blob,json=encryptedSekBlob,proto3" json:"encrypted_sek_blob,omitempty"`
}

func (x *GenerateSEKResponse) Reset() {
	*x = GenerateSEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSEKResponse) ProtoMessage() {}

func (x *GenerateSEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSEKResponse.ProtoReflect.Descriptor instead.
func (*GenerateSEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateSEKResponse) GetEncryptedSekBlob() []byte {
	if x != nil {
		return x.EncryptedSekBlob
	}
	return nil
}

type LoadSEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Encrypted blob of DEK
	EncryptedDekBlob []byte `protobuf:"bytes,1,opt,name=encrypted_dek_blob,json=encryptedDekBlob,proto3" json:"encrypted_dek_blob,omitempty"`
	// Encrypted blob of SEK
	EncryptedSekBlob []byte `protobuf:"bytes,2,opt,name=encrypted_sek_blob,json=encryptedSekBlob,proto3" json:"encrypted_sek_blob,omitempty"`
	// KEK
	KekKid []byte `protobuf:"bytes,3,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,4,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *LoadSEKRequest) Reset() {
	*x = LoadSEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadSEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSEKRequest) ProtoMessage() {}

func (x *LoadSEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSEKRequest.ProtoReflect.Descriptor instead.
func (*LoadSEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *LoadSEKRequest) GetEncryptedDekBlob() []byte {
	if x != nil {
		return x.EncryptedDekBlob
	}
	return nil
}

func (x *LoadSEKRequest) GetEncryptedSekBlob() []byte {
	if x != nil {
		return x.EncryptedSekBlob
	}
	return nil
}

func (x *LoadSEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

func (x *LoadSEKRequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type LoadSEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Clear SEK
	ClearSek []byte `protobuf:"bytes,1,opt,name=clear_sek,json=clearSek,proto3" json:"clear_sek,omitempty"`
}

func (x *LoadSEKResponse) Reset() {
	*x = LoadSEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadSEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSEKResponse) ProtoMessage() {}

func (x *LoadSEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSEKResponse.ProtoReflect.Descriptor instead.
func (*LoadSEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *LoadSEKResponse) GetClearSek() []byte {
	if x != nil {
		return x.ClearSek
	}
	return nil
}

type SignCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Encrypted blob of DEK
	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,2,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *SignCSRRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *SignCSRRequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type SignCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Certificate in PEM Form
	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_istio_v1_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_istio_v1_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_apis_istio_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *SignCSRResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

var File_apis_istio_v1_messages_proto protoreflect.FileDescriptor

var file_apis_istio_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a,
	0x74, 0x68, 0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2e, 0x69, 0x6f, 0x2e, 0x65, 0x6b, 0x6d,
	0x73, 0x2e, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x7a, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x44, 0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x37, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x74, 0x68, 0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2e, 0x69, 0x6f, 0x2e, 0x65, 0x6b,
	0x6d, 0x73, 0x2e, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b,
	0x5f, 0x6b, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b,
	0x69, 0x64, 0x22, 0x43, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x45,
	0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x6b, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x44, 0x65, 0x6b, 0x42, 0x6c, 0x6f, 0x62, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x74, 0x68, 0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2e, 0x69, 0x6f, 0x2e,
	0x65, 0x6b, 0x6d, 0x73, 0x2e, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65,
	0x79, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x13, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b,
	0x69, 0x64, 0x22, 0x33, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x41,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f,
	0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x65, 0x72,
	0x74, 0x22, 0x30, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x6f, 0x6f, 0x74,
	0x43, 0x41, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65,
	0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b,
	0x4b, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x6f,
	0x6f, 0x74, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xd6, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x53, 0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x74, 0x68, 0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2e, 0x69, 0x6f, 0x2e,
	0x65, 0x6b, 0x6d, 0x73, 0x2e, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65,
	0x79, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x6b, 0x5f, 0x62, 0x6c, 0x6f,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x44, 0x65, 0x6b, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x6b, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x6b, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x45, 0x4b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x6b, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x65,
	0x6b, 0x42, 0x6c, 0x6f, 0x62, 0x22, 0xa5, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x45,
	0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x6b, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44,
	0x65, 0x6b, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x6b, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x53, 0x65, 0x6b,
	0x42, 0x6c, 0x6f, 0x62, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69, 0x64, 0x22, 0x2e, 0x0a,
	0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x73, 0x65, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x53, 0x65, 0x6b, 0x22, 0x42, 0x0a,
	0x0e, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x73, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x73,
	0x72, 0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69,
	0x64, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x2a, 0x31, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x45, 0x53, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x53, 0x41,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x43, 0x43, 0x10, 0x03, 0x42, 0x3c, 0x5a, 0x3a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x61, 0x6c, 0x65, 0x73,
	0x63, 0x70, 0x6c, 0x2d, 0x69, 0x6f, 0x2f, 0x6b, 0x38, 0x73, 0x2d, 0x6b, 0x6d, 0x73, 0x2d, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x73, 0x74, 0x69, 0x6f,
	0x2f, 0x76, 0x31, 0x3b, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_apis_istio_v1_messages_proto_rawDescOnce sync.Once
	file_apis_istio_v1_messages_proto_rawDescData = file_apis_istio_v1_messages_proto_rawDesc
)

func file_apis_istio_v1_messages_proto_rawDescGZIP() []byte {
	file_apis_istio_v1_messages_proto_rawDescOnce.Do(func() {
		file_apis_istio_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_istio_v1_messages_proto_rawDescData)
	})
	return file_apis_istio_v1_messages_proto_rawDescData
}

var file_apis_istio_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apis_istio_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_apis_istio_v1_messages_proto_goTypes = []interface{}{
	(KeyKind)(0),                   // 0: thalescpl.io.ekms.istio.v1.KeyKind
	(*GenerateKEKRequest)(nil),     // 1: thalescpl.io.ekms.istio.v1.GenerateKEKRequest
	(*GenerateKEKResponse)(nil),    // 2: thalescpl.io.ekms.istio.v1.GenerateKEKResponse
	(*DestroyKEKRequest)(nil),      // 3: thalescpl.io.ekms.istio.v1.DestroyKEKRequest
	(*DestroyKEKResponse)(nil),     // 4: thalescpl.io.ekms.istio.v1.DestroyKEKResponse
	(*GenerateDEKRequest)(nil),     // 5: thalescpl.io.ekms.istio.v1.GenerateDEKRequest
	(*GenerateDEKResponse)(nil),    // 6: thalescpl.io.ekms.istio.v1.GenerateDEKResponse
	(*GenerateCAKRequest)(nil),     // 7: thalescpl.io.ekms.istio.v1.GenerateCAKRequest
	(*GenerateCAKResponse)(nil),    // 8: thalescpl.io.ekms.istio.v1.GenerateCAKResponse
	(*GenerateCARequest)(nil),      // 9: thalescpl.io.ekms.istio.v1.GenerateCARequest
	(*GenerateCAResponse)(nil),     // 10: thalescpl.io.ekms.istio.v1.GenerateCAResponse
	(*DestroyRootCAKRequest)(nil),  // 11: thalescpl.io.ekms.istio.v1.DestroyRootCAKRequest
	(*DestroyRootCAKResponse)(nil), // 12: thalescpl.io.ekms.istio.v1.DestroyRootCAKResponse
	(*GenerateSEKRequest)(nil),     // 13: thalescpl.io.ekms.istio.v1.GenerateSEKRequest
	(*GenerateSEKResponse)(nil),    // 14: thalescpl.io.ekms.istio.v1.GenerateSEKResponse
	(*LoadSEKRequest)(nil),         // 15: thalescpl.io.ekms.istio.v1.LoadSEKRequest
	(*LoadSEKResponse)(nil),        // 16: thalescpl.io.ekms.istio.v1.LoadSEKResponse
	(*SignCSRRequest)(nil),         // 17: thalescpl.io.ekms.istio.v1.SignCSRRequest
	(*SignCSRResponse)(nil),        // 18: thalescpl.io.ekms.istio.v1.SignCSRResponse
}
var file_apis_istio_v1_messages_proto_depIdxs = []int32{
	0, // 0: thalescpl.io.ekms.istio.v1.GenerateDEKRequest.kind:type_name -> thalescpl.io.ekms.istio.v1.KeyKind
	0, // 1: thalescpl.io.ekms.istio.v1.GenerateCAKRequest.kind:type_name -> thalescpl.io.ekms.istio.v1.KeyKind
	0, // 2: thalescpl.io.ekms.istio.v1.GenerateSEKRequest.kind:type_name -> thalescpl.io.ekms.istio.v1.KeyKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_apis_istio_v1_messages_proto_init() }
func file_apis_istio_v1_messages_proto_init() {
	if File_apis_istio_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_istio_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyKEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyKEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCAKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCAKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRootCAKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyRootCAKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadSEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadSEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_istio_v1_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_istio_v1_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_istio_v1_messages_proto_goTypes,
		DependencyIndexes: file_apis_istio_v1_messages_proto_depIdxs,
		EnumInfos:         file_apis_istio_v1_messages_proto_enumTypes,
		MessageInfos:      file_apis_istio_v1_messages_proto_msgTypes,
	}.Build()
	File_apis_istio_v1_messages_proto = out.File
	file_apis_istio_v1_messages_proto_rawDesc = nil
	file_apis_istio_v1_messages_proto_goTypes = nil
	file_apis_istio_v1_messages_proto_depIdxs = nil
}
