// Code generated by go-swagger; DO NOT EDIT.

// Package restapi est server
//
//  RFC 7030 (EST) server implementation
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /.well-known/est
//  Version: 1.0.0
//
//  Consumes:
//    - application/pkcs10
//
//  Produces:
//    - application/pkcs7-mime
//    - text/plain
//
// swagger:meta
package restapi
