// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "RFC 7030 (EST) server implementation",
    "title": "est server",
    "version": "1.0.0"
  },
  "basePath": "/.well-known/est",
  "paths": {
    "/cacerts": {
      "get": {
        "description": "Distributes CA Certificate chain for this Service",
        "produces": [
          "application/pkcs7-mime"
        ],
        "tags": [
          "operation"
        ],
        "summary": "Distribution of CA Certificates",
        "operationId": "GetCACerts",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {
              "Content-Transfer-Encoding": {
                "type": "string",
                "default": "base64"
              },
              "Content-Type": {
                "type": "string",
                "default": "application/pkcs7-mime"
              }
            }
          },
          "500": {
            "description": "something went wrong",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/simpleenroll": {
      "post": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "consumes": [
          "application/pkcs10"
        ],
        "produces": [
          "text/plain"
        ],
        "tags": [
          "operation"
        ],
        "summary": "Enrollment of Clients",
        "operationId": "simpleenroll",
        "parameters": [
          {
            "description": "PKCS10 certificate request (DER format, base64 encoded)",
            "name": "certrequest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {
              "Content-Transfer-Encoding": {
                "type": "string",
                "default": "base64"
              },
              "Content-Type": {
                "type": "string",
                "default": "application/pkcs7-mime"
              }
            }
          },
          "400": {
            "description": "invalid request",
            "schema": {
              "type": "string"
            }
          },
          "401": {
            "description": "unauthorized",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "something went wrong",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/simplereenroll": {
      "post": {
        "consumes": [
          "application/pkcs10"
        ],
        "produces": [
          "text/plain"
        ],
        "tags": [
          "operation"
        ],
        "summary": "Enrollment of Clients (requires mutual-tls)",
        "operationId": "simplereenroll",
        "parameters": [
          {
            "description": "PKCS10 certificate request (DER format, base64 encoded)",
            "name": "certrequest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {
              "Content-Transfer-Encoding": {
                "type": "string",
                "default": "base64"
              },
              "Content-Type": {
                "type": "string",
                "default": "application/pkcs7-mime"
              }
            }
          },
          "400": {
            "description": "invalid request",
            "schema": {
              "type": "string"
            }
          },
          "403": {
            "description": "client certificates were not presented",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "something went wrong",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  },
  "tags": [
    {
      "description": "RFC 7030 operations",
      "name": "operation"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "RFC 7030 (EST) server implementation",
    "title": "est server",
    "version": "1.0.0"
  },
  "basePath": "/.well-known/est",
  "paths": {
    "/cacerts": {
      "get": {
        "description": "Distributes CA Certificate chain for this Service",
        "produces": [
          "application/pkcs7-mime"
        ],
        "tags": [
          "operation"
        ],
        "summary": "Distribution of CA Certificates",
        "operationId": "GetCACerts",
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {
              "Content-Transfer-Encoding": {
                "type": "string",
                "default": "base64"
              },
              "Content-Type": {
                "type": "string",
                "default": "application/pkcs7-mime"
              }
            }
          },
          "500": {
            "description": "something went wrong",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/simpleenroll": {
      "post": {
        "security": [
          {
            "basicAuth": []
          }
        ],
        "consumes": [
          "application/pkcs10"
        ],
        "produces": [
          "text/plain"
        ],
        "tags": [
          "operation"
        ],
        "summary": "Enrollment of Clients",
        "operationId": "simpleenroll",
        "parameters": [
          {
            "description": "PKCS10 certificate request (DER format, base64 encoded)",
            "name": "certrequest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {
              "Content-Transfer-Encoding": {
                "type": "string",
                "default": "base64"
              },
              "Content-Type": {
                "type": "string",
                "default": "application/pkcs7-mime"
              }
            }
          },
          "400": {
            "description": "invalid request",
            "schema": {
              "type": "string"
            }
          },
          "401": {
            "description": "unauthorized",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "something went wrong",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/simplereenroll": {
      "post": {
        "consumes": [
          "application/pkcs10"
        ],
        "produces": [
          "text/plain"
        ],
        "tags": [
          "operation"
        ],
        "summary": "Enrollment of Clients (requires mutual-tls)",
        "operationId": "simplereenroll",
        "parameters": [
          {
            "description": "PKCS10 certificate request (DER format, base64 encoded)",
            "name": "certrequest",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            },
            "headers": {
              "Content-Transfer-Encoding": {
                "type": "string",
                "default": "base64"
              },
              "Content-Type": {
                "type": "string",
                "default": "application/pkcs7-mime"
              }
            }
          },
          "400": {
            "description": "invalid request",
            "schema": {
              "type": "string"
            }
          },
          "403": {
            "description": "client certificates were not presented",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "something went wrong",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  },
  "tags": [
    {
      "description": "RFC 7030 operations",
      "name": "operation"
    }
  ]
}`))
}
