//
// * // Copyright 2024 Thales Group 2020 Thales DIS CPL Inc
// * //
// * // Permission is hereby granted, free of charge, to any person obtaining
// * // a copy of this software and associated documentation files (the
// * // "Software"), to deal in the Software without restriction, including
// * // without limitation the rights to use, copy, modify, merge, publish,
// * // distribute, sublicense, and/or sell copies of the Software, and to
// * // permit persons to whom the Software is furnished to do so, subject to
// * // the following conditions:
// * //
// * // The above copyright notice and this permission notice shall be
// * // included in all copies or substantial portions of the Software.
// * //
// * // THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// * // EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// * // MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// * // NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// * // LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// * // OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// * // WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.10.0
// source: apis/kms/v1/messages.proto

package kms

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KeyKind int32

const (
	KeyKind_UNKNOWN KeyKind = 0
	KeyKind_AES     KeyKind = 1
	KeyKind_RSA     KeyKind = 2
	KeyKind_ECC     KeyKind = 3
)

// Enum value maps for KeyKind.
var (
	KeyKind_name = map[int32]string{
		0: "UNKNOWN",
		1: "AES",
		2: "RSA",
		3: "ECC",
	}
	KeyKind_value = map[string]int32{
		"UNKNOWN": 0,
		"AES":     1,
		"RSA":     2,
		"ECC":     3,
	}
)

func (x KeyKind) Enum() *KeyKind {
	p := new(KeyKind)
	*p = x
	return p
}

func (x KeyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_kms_v1_messages_proto_enumTypes[0].Descriptor()
}

func (KeyKind) Type() protoreflect.EnumType {
	return &file_apis_kms_v1_messages_proto_enumTypes[0]
}

func (x KeyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyKind.Descriptor instead.
func (KeyKind) EnumDescriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{0}
}

type VersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version of the KMS plugin API.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type VersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version of the KMS plugin API.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Name of the KMS provider.
	RuntimeName string `protobuf:"bytes,2,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	// Version of the KMS provider. The string must be semver-compatible.
	RuntimeVersion string `protobuf:"bytes,3,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *VersionResponse) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

type GenerateKEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// optional kid, otherwise will be autogenerated as a UUID.v4 in the response
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *GenerateKEKRequest) Reset() {
	*x = GenerateKEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEKRequest) ProtoMessage() {}

func (x *GenerateKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEKRequest.ProtoReflect.Descriptor instead.
func (*GenerateKEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type GenerateKEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// KEK kid
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *GenerateKEKResponse) Reset() {
	*x = GenerateKEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEKResponse) ProtoMessage() {}

func (x *GenerateKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEKResponse.ProtoReflect.Descriptor instead.
func (*GenerateKEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateKEKResponse) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyKEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required kid of KEK to find and delete
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *DestroyKEKRequest) Reset() {
	*x = DestroyKEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyKEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEKRequest) ProtoMessage() {}

func (x *DestroyKEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEKRequest.ProtoReflect.Descriptor instead.
func (*DestroyKEKRequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyKEKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyKEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// successful destroy?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DestroyKEKResponse) Reset() {
	*x = DestroyKEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyKEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEKResponse) ProtoMessage() {}

func (x *DestroyKEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEKResponse.ProtoReflect.Descriptor instead.
func (*DestroyKEKResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DestroyKEKResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GenerateCAKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key size in bits
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// What kind of key is it... only Asymmetric kinds will be supported
	Kind KeyKind `protobuf:"varint,2,opt,name=kind,proto3,enum=thalescpl.io.ekms.kms.v1.KeyKind" json:"kind,omitempty"`
	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,3,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *GenerateCAKRequest) Reset() {
	*x = GenerateCAKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCAKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCAKRequest) ProtoMessage() {}

func (x *GenerateCAKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCAKRequest.ProtoReflect.Descriptor instead.
func (*GenerateCAKRequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateCAKRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateCAKRequest) GetKind() KeyKind {
	if x != nil {
		return x.Kind
	}
	return KeyKind_UNKNOWN
}

func (x *GenerateCAKRequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type GenerateCAKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,1,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *GenerateCAKResponse) Reset() {
	*x = GenerateCAKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCAKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCAKResponse) ProtoMessage() {}

func (x *GenerateCAKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCAKResponse.ProtoReflect.Descriptor instead.
func (*GenerateCAKResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateCAKResponse) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type GenerateCARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,1,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *GenerateCARequest) Reset() {
	*x = GenerateCARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCARequest) ProtoMessage() {}

func (x *GenerateCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCARequest.ProtoReflect.Descriptor instead.
func (*GenerateCARequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateCARequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type GenerateCAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Root CA cert in PEM format
	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *GenerateCAResponse) Reset() {
	*x = GenerateCAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCAResponse) ProtoMessage() {}

func (x *GenerateCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCAResponse.ProtoReflect.Descriptor instead.
func (*GenerateCAResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateCAResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

type DestroyCAKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required kid of KEK to find and delete
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *DestroyCAKRequest) Reset() {
	*x = DestroyCAKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyCAKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCAKRequest) ProtoMessage() {}

func (x *DestroyCAKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCAKRequest.ProtoReflect.Descriptor instead.
func (*DestroyCAKRequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyCAKRequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyCAKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// successful destroy?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DestroyCAKResponse) Reset() {
	*x = DestroyCAKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyCAKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCAKResponse) ProtoMessage() {}

func (x *DestroyCAKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCAKResponse.ProtoReflect.Descriptor instead.
func (*DestroyCAKResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyCAKResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DestroyCARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required kid of KEK to find and delete
	KekKid []byte `protobuf:"bytes,1,opt,name=kek_kid,json=kekKid,proto3" json:"kek_kid,omitempty"`
}

func (x *DestroyCARequest) Reset() {
	*x = DestroyCARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCARequest) ProtoMessage() {}

func (x *DestroyCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCARequest.ProtoReflect.Descriptor instead.
func (*DestroyCARequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DestroyCARequest) GetKekKid() []byte {
	if x != nil {
		return x.KekKid
	}
	return nil
}

type DestroyCAResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// successful destroy?
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DestroyCAResponse) Reset() {
	*x = DestroyCAResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCAResponse) ProtoMessage() {}

func (x *DestroyCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCAResponse.ProtoReflect.Descriptor instead.
func (*DestroyCAResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *DestroyCAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SignCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Encrypted blob of DEK
	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	// Root CA Key ID
	RootCaKid []byte `protobuf:"bytes,2,opt,name=root_ca_kid,json=rootCaKid,proto3" json:"root_ca_kid,omitempty"`
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SignCSRRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *SignCSRRequest) GetRootCaKid() []byte {
	if x != nil {
		return x.RootCaKid
	}
	return nil
}

type SignCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Certificate in PEM Form
	Cert []byte `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apis_kms_v1_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_kms_v1_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_apis_kms_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SignCSRResponse) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

var File_apis_kms_v1_messages_proto protoreflect.FileDescriptor

var file_apis_kms_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6b, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x74, 0x68,
	0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2e, 0x69, 0x6f, 0x2e, 0x65, 0x6b, 0x6d, 0x73, 0x2e,
	0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x77, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x4b, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x7f, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x35, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x21, 0x2e, 0x74, 0x68, 0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2e, 0x69, 0x6f, 0x2e, 0x65,
	0x6b, 0x6d, 0x73, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74,
	0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72,
	0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69, 0x64, 0x22,
	0x33, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x41, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f,
	0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43,
	0x61, 0x4b, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x43, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0x2c,
	0x0a, 0x11, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x41, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2b, 0x0a, 0x10,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x6b, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x6b, 0x65, 0x6b, 0x4b, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x43, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e,
	0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x73,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x73, 0x72, 0x12, 0x1e, 0x0a, 0x0b,
	0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x4b, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f,
	0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63,
	0x65, 0x72, 0x74, 0x2a, 0x31, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x45, 0x53, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x53, 0x41, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x45, 0x43, 0x43, 0x10, 0x03, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x61, 0x6c, 0x65, 0x73, 0x63, 0x70, 0x6c, 0x2d, 0x69,
	0x6f, 0x2f, 0x6b, 0x38, 0x73, 0x2d, 0x6b, 0x6d, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6b, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6b, 0x6d, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apis_kms_v1_messages_proto_rawDescOnce sync.Once
	file_apis_kms_v1_messages_proto_rawDescData = file_apis_kms_v1_messages_proto_rawDesc
)

func file_apis_kms_v1_messages_proto_rawDescGZIP() []byte {
	file_apis_kms_v1_messages_proto_rawDescOnce.Do(func() {
		file_apis_kms_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_apis_kms_v1_messages_proto_rawDescData)
	})
	return file_apis_kms_v1_messages_proto_rawDescData
}

var file_apis_kms_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apis_kms_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apis_kms_v1_messages_proto_goTypes = []interface{}{
	(KeyKind)(0),                // 0: thalescpl.io.ekms.kms.v1.KeyKind
	(*VersionRequest)(nil),      // 1: thalescpl.io.ekms.kms.v1.VersionRequest
	(*VersionResponse)(nil),     // 2: thalescpl.io.ekms.kms.v1.VersionResponse
	(*GenerateKEKRequest)(nil),  // 3: thalescpl.io.ekms.kms.v1.GenerateKEKRequest
	(*GenerateKEKResponse)(nil), // 4: thalescpl.io.ekms.kms.v1.GenerateKEKResponse
	(*DestroyKEKRequest)(nil),   // 5: thalescpl.io.ekms.kms.v1.DestroyKEKRequest
	(*DestroyKEKResponse)(nil),  // 6: thalescpl.io.ekms.kms.v1.DestroyKEKResponse
	(*GenerateCAKRequest)(nil),  // 7: thalescpl.io.ekms.kms.v1.GenerateCAKRequest
	(*GenerateCAKResponse)(nil), // 8: thalescpl.io.ekms.kms.v1.GenerateCAKResponse
	(*GenerateCARequest)(nil),   // 9: thalescpl.io.ekms.kms.v1.GenerateCARequest
	(*GenerateCAResponse)(nil),  // 10: thalescpl.io.ekms.kms.v1.GenerateCAResponse
	(*DestroyCAKRequest)(nil),   // 11: thalescpl.io.ekms.kms.v1.DestroyCAKRequest
	(*DestroyCAKResponse)(nil),  // 12: thalescpl.io.ekms.kms.v1.DestroyCAKResponse
	(*DestroyCARequest)(nil),    // 13: thalescpl.io.ekms.kms.v1.DestroyCARequest
	(*DestroyCAResponse)(nil),   // 14: thalescpl.io.ekms.kms.v1.DestroyCAResponse
	(*SignCSRRequest)(nil),      // 15: thalescpl.io.ekms.kms.v1.SignCSRRequest
	(*SignCSRResponse)(nil),     // 16: thalescpl.io.ekms.kms.v1.SignCSRResponse
}
var file_apis_kms_v1_messages_proto_depIdxs = []int32{
	0, // 0: thalescpl.io.ekms.kms.v1.GenerateCAKRequest.kind:type_name -> thalescpl.io.ekms.kms.v1.KeyKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apis_kms_v1_messages_proto_init() }
func file_apis_kms_v1_messages_proto_init() {
	if File_apis_kms_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apis_kms_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyKEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyKEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCAKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCAKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateCAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyCAKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyCAKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyCARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyCAResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apis_kms_v1_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_kms_v1_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apis_kms_v1_messages_proto_goTypes,
		DependencyIndexes: file_apis_kms_v1_messages_proto_depIdxs,
		EnumInfos:         file_apis_kms_v1_messages_proto_enumTypes,
		MessageInfos:      file_apis_kms_v1_messages_proto_msgTypes,
	}.Build()
	File_apis_kms_v1_messages_proto = out.File
	file_apis_kms_v1_messages_proto_rawDesc = nil
	file_apis_kms_v1_messages_proto_goTypes = nil
	file_apis_kms_v1_messages_proto_depIdxs = nil
}
