# k8s-kms-plugin configuration file example
  
k8s-kms-plugin:
  # Cobra root flags
  ## Logging settings
  ### log-level possible values: trace, debug, info, warning, error, fatal and panic.
  log-level: "trace"
  ### debug possible values: true, false. In the configuration file, it is recommended to use log-level over debug (they are mutually exclusive).
  #debug: false
  ### log-format possible values: text, json
  log-format: "json"
  
  # Cobra subcommands
  serve:
    ## algorithm possible values: aes-gcm, aes-cbc, rsa-oaep
    algorithm: "rsa-oaep"
    allow-any: false

    ## TLS settings
    tls-ca: "certs/ca.crt"
    tls-key: "certs/tls.key"
    tls-certificate: "certs/tls.crt"

    ## Server settings
    disable-socket: false
    enable-server: true
    host: "127.0.0.1"
    port: 8080
    socket: "/var/run/kms-plugin.sock"
    
    ## KMS settings
    ### provider possible values: p11, softhsm, luna, dpod.
    provider: "p11"
    kek-id: "my-key"
    ca-id: "my-ca"
    
    p11-lib: "/usr/local/lib/softhsm/libsofthsm2.so"
    p11-label: "my-current-label"
    p11-slot: 0
    p11-pin: "1234" # This is a secret, you set this with an environment variable K8S_KMS_PLUGIN_SERVE_P11_PIN instead of the configuration file
  
  version:
    # Format of the version output. One of 'yaml' or 'json'.
    output: "json"
    pretty: true # only for JSON output