@startuml "Kubernetes KMS v2 Decrypt Request & Response"

'=============================================================================='
'== PlantUML Appearance parameters ============================================'
'=============================================================================='
skinparam shadowing false
'skinparam backgroundColor transparent

' enable arrows on same level
'!pragma teoz true

skinparam legend {
  FontSize 13
  FontName DejaVu Sans Mono
  BorderColor black
  BackgroundColor white
}

skinparam sequence {
ArrowColor Black
ActorBorderColor Black
LifeLineBorderColor Black
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor MidnightBlue
ParticipantBackgroundColor #326CE5
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor white

ActorBackgroundColor MidnightBlue
ActorFontColor MidnightBlue
ActorFontSize 17
ActorFontName Aapex
}

skinparam ArrowFontName DejaVu Sans Mono


'=============================================================================='
'== Title ====================================================================='
'=============================================================================='
title
    KMS v2 Decrypt Request & Response
    Kubernetes KMS API v2 - k8s.io/kms/apis/v2 & KMS Plugin for PKCS #11
end title

skinparam HeaderFontSize 14
header <font color=black>Kubernetes KMS v2 & k8s-kms-plugin Figure %page% of %lastpage%</font>
footer © 2025 Thales Group for Thales Open Source

' Legend
legend top left
    Legend
    CKA_ID (Byte array) PKCS #11 Key identifier for public/private key pairs
    DEK    Data Encryption Key
    JWE    JSON Web Encryption
    KEK    Key Encryption Key
    KMS    Key Management System
    HSM    Hardware Security Module
    TPM    Trusted Platform Module
    
    PKCS #11 v3.0: https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/pkcs11-base-v3.0.html
    KMS v2: - https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/
            - https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements
end legend

'=============================================================================='
'== Sequence diagram begins ==================================================='
'=============================================================================='

    actor "k8s admin" as k8sa
    actor "kms admin" as kmsa

    box "kubernetes" #AliceBlue
        participant "k8s apiserver" as k8sapisrv
        participant "etcd" as etcd
    end box


    box "kms plugin & PKCS #11 TPM/HSM" #fff
        participant "k8s-kms-plugin (server)" as kmsplg
        participant "pkcs11-device" as p11
    end box

    group KMS v2 & Kubernetes node restart
        note over k8sa, etcd : After a kubernetes reboot, k8s sends both a first StatusRequest to know which key id is active. \nk8s generates a new DEK seed and a corresponding EncryptionRequest in case the key id changed. \nk8s sends as many DecryptRequests as their are encrypted DEK seeds in ETCD; preferably it should \nnot be more than 2 different DEKs at the same time. This happens during a key rotation.

        k8sa -> k8sapisrv : Reboot a kubernetes \nserver node

        note over kmsa, kmsplg : Case: KEK Key Id from the k8s-kms-plugin is the same than before k8s reboot (same KEK)

            group KMS v2 first StatusRequest
                k8sapisrv -> kmsplg : send StatusRequest
                kmsplg -> p11 : validate remote KEK, e.g. \n get CKA_ID from TPM/HSM
                p11 -> kmsplg : return KEK status, e.g. CKA_ID
                kmsplg -> k8sapisrv : return StatusResponse \n {Version:"v2", Healthz: "ok", \n KeyId:<remote KEK ID string, the same than before k8s reboot>}
            end

            k8sapisrv -> etcd : get encrypted resource
            etcd -> k8sapisrv : return encrypted resource

        loop For active KEK and all the old KEK Keys (As many different Key Ids) that still exist in the ETCD DB, do a DecryptRequest.
            group DecryptRequest
                k8sapisrv -> kmsplg : send DecryptRequest \n {Ciphertext: <base 64 encoded JWE []byte>, KeyId:<string>, \n Uid:<string>, Annotations: <map[string][]byte>}
                kmsplg -> p11 : Decrypt(Ciphertext) \n decrypt DEK seed with remote KEK
                kmsplg <- p11 : return decrypted DEK seed
                kmsplg -> k8sapisrv : return DecryptResponse \n {Plaintext:<decrypted DEK seed []byte>}
            end

            k8sapisrv -> k8sapisrv : cache decrypted DEK seed
            k8sapisrv -> k8sapisrv : generate DEK using decrypted DEK seed from cache
            k8sapisrv -> k8sapisrv : decrypt resource with DEK
        end
    end
@enduml