@startuml
    actor "k8s admin" as k8sa

    box "k8s" #LightBlue
        participant "APIServer" as apis
    end box

    box "kms" #fff
        participant "k8s-kms-plugin-server" as server
        participant "pkcs11-device" as p11
    end box

    group Register KMS to K8S
        k8sa -> apis : Configure KMS Plugin Parameters

    end

    group Startup Sequences
        server -> p11 : Load or AutoCreate KEK(Lib, Slot, PIN, KID)
        p11 -> server : KEK Loaded
    end

    group K8S Data Protection Operations

        apis -> server : Encrypt(EncryptRequest)
        server -> p11 : Encrypt(Clear)
        server <- p11 : Encrypt(CipherText)
        apis <- server : Encrypt(EncryptResponse)

        apis -> server : Decrypt(DecryptRequest)
        server -> p11 : Decrypt(CipherText)
        server <- p11 : Decrypt(Clear)
        apis <- server : Decrypt(DecryptResponse)

    end


    group General Purpose PKI Operations
        apis -> server :
    end
    actor "kms admin" as kmsa

@enduml
