name : Build Binary
on:
    push:
      
jobs:
    build: 
        name: upload-binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: build-binary
              run: |
               go get github.com/miekg/pkcs11@v1.0.3-0.20190429190417-a667d056470f
               go mod vendor
               make build
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: k8s-kms-plugin
                path: k8s-kms-plugin
            