name : Build Plugin
on:
    push:
      
      
jobs:
    buildX64: 
        name: Build Plugin on AMDx86
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v3
            #Change the go version of the runner.
            - uses : actions/setup-go@v4
              with:
                go-version: '1.21'
            #Build the k8s-kms-plugin in the runner environment.
            - name: build-binary on AMD
              run: |

               long="${{ github.ref }}"; version=${long#"refs/tags/v"}; short=${long#"refs/tags/"};
               # Building plugin

               go mod tidy
               go mod vendor
               make build

               #Creating Debian Package

               mkdir -p k8s-kms/usr/bin
               mkdir -p k8s-kms/usr/lib/k8s-kms-plugin
               cp k8s-kms-plugin k8s-kms/usr/bin/k8s-kms-plugin
               chmod +x k8s-kms/usr/bin/k8s-kms-plugin
               mkdir -p k8s-kms/DEBIAN
               touch k8s-kms/DEBIAN/control
               echo -e "Package: k8s-kms-plugin\nDescription: k8-kms-plugin package\nMaintainer: ${{github.repository_owner}}\nVersion: "${version}"\nArchitecture: amd64 " > k8s-kms/DEBIAN/control
               dpkg --build k8s-kms
            #Upload k8s-kms-plugin into the artifacts depository of github.
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: k8s-kms-plugin${{github.ref_name}}-x64
                path: k8s-kms-plugin
            - uses: actions/upload-artifact@v4
              with:
                name: k8s-kms-plugin${{github.ref_name}}-deb
                path: k8s-kms.deb
               