name : Build Plugin
on:
    push:
      
jobs:
    build: 
        name: Build Plugin
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            #Change the go version of the runner.
            - uses : actions/setup-go@v4
              with:
                go-version: '1.21'
            #Build the k8s-kms-plugin in the runner environment.
            - name: build-binary
              run: |
               go mod tidy
               go mod vendor
               make build
            #Upload k8s-kms-plugin into the artifacts depository of github.
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: k8s-kms-plugin
                path: k8s-kms-plugin