name : Create Release
on:
  workflow_run:
    workflows: ["Scan Dependencies"]
    types: [completed]
      
jobs:
    build: 
        name: Create Release
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4clear
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    syft-sbom.SPDX${{ github.ref_name }}.json
                    syft-sbom.Cyclonedx${{ github.ref_name }}.json
                    k8s-kms-plugin${{ github.ref_name }}
                    k8s-kms${{ github.ref_name }}.deb