name: Create a Github Release

on:
  workflow_run:
    workflows:
      - Scan Dependencies
    types:
      - completed

jobs:
  on-success:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            syft-sbom.SPDX.json
            syft-sbom.CycloneDX.json
            k8s-kms-plugin
