name : Scan Dependencies & SBOM
on:
  workflow_run:
    workflows: ["Build Plugin"]
    types: [completed]
      
jobs:
    build: 
        name: Scan Dependencies
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4clear
            #Use the scanner Syft to generate a SPDX format's SBOM of the code.
            - name: syft-scan-CycloneDx
              uses: anchore/sbom-action@v0
              with:
                format: cyclonedx-json
                artifact-name: syft-sbom.Cyclonedx.json
            #Use the scanner Syft to generate a CycloneDX format's SBOM of the code.
            - name: syft-scan-SPDX
              uses: anchore/sbom-action@v0
              with:
                artifact-name: syft-sbom.SPDX.json
           