name : Scan Dependencies
on:
    push:
      
jobs:
    build: 
        name: Scan Dependencies
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            #Change the go version of the runner.
            - uses : actions/setup-go@v4
              with:
                go-version: '1.21'
            #Build the k8s-kms-plugin in the runner environment.
            - name: build-binary
              run: |
               go mod tidy
               go mod vendor
               make build
            #Upload k8s-kms-plugin into the artifacts depository of github.
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: k8s-kms-plugin
                path: k8s-kms-plugin
            #Use the scanner Syft to generate a SPDX format's SBOM of the code.
            - name: syft-scan-CycloneDx
              uses: anchore/sbom-action@v0
              with:
                format: cyclonedx-json
                artifact-name: syft-sbom.Cyclonedx
            #Use the scanner Syft to generate a CycloneDX format's SBOM of the code.
            - name: syft-scan-SPDX
              uses: anchore/sbom-action@v0
              with:
                artifact-name: syft-sbom.SPDX
            #Generate a Release if the branch has a tag. The release contains the different format SBOM and the k8s-kms-plugin.
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    syft-sbom.SPDX
                    syft-sbom.Cyclonedx
                    k8s-kms-plugin