name: Scan Dependencies

on:
  workflow_run:
    workflows:
      - Build k8s-kms-plugin
    types:
      - completed

jobs:
  on-success:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4clear
      - name: syft-scan-CycloneDX
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          artifact-name: syft-sbom.CycloneDX.json
      - name: syft-scan-SPDX
        uses: anchore/sbom-action@v0
        with:
          artifact-name: syft-sbom.SPDX.json
